---
title: "Coutts Agro Ltd. Risk Transfer"
description: |
  Risk transfer strategy for Coutss Agro Ltd., 2021 season.
author:
  - name: Melanie Bacou 
    url: https://linkedin.com/in/mbacou
    affiliation: WorldCover PBC
    affiliation_url: https://worldcovr.com/
date: 04-01-2021
categories:
  - meteo
  - risk modeling
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}

library(scales)
library(knitr)
library(ggside)
library(thematic)
library(data.table)
library(maptiles)
library(raster)
library(terra)
library(wcutils)

opts_chunk$set(dev="ragg_png", dpi=220)
load("data.RData")
dir <- getOption("wc.data")

# Plot defaults
thematic_on("transparent", "#000000", c("#008080", "#87aab4"), 
  font_spec("Lato"),
  qualitative = c(
    "#008080", "#51676f", "#233b5d", "#772d42", 
    "#c58f69", "#ef5b84", "#09585d", "#87aab4"))

scale_fill_wc <- function(low="#ffffff", high="#008080", ...) scale_fill_gradient(
  low=low, high=high, ...)

```

```{r gsod, fig.width=6, fig.height=5}

# Obtained from NOAA GSOD
cdo.dt <- rbind(
  fread("./data/CDO_Praia_1973-2021.csv"),
  fread("./data/CDO_Amilcar_1973-2021.csv")
)

setnames(cdo.dt, c(
  STATION="loc_id",
  NAME = "loc_nm",
  LATITUDE = "Y",
  LONGITUDE = "X",
  ELEVATION = "Z",
  DATE = "date",
  PRCP = "prcp",
  tavg = "tavg",
  TMIN = "tmin",
  TMAX = "tmax"
))

tmp <- cdo.dt[, .N, by=.(loc_id, loc_nm, X, Y, Z)]
cdo <- SpatialPointsDataFrame(tmp[, .(X, Y)], data.frame(tmp),
  proj4string=CRS("+init=epsg:4326"))

# Completeness
tmp <- cdo.dt[, .(date=seq(min(date), max(date), by="day")), by=.(loc_id, loc_nm)]
cdo.dt <- cdo.dt[tmp, on=.(loc_id, loc_nm, date)]
kable(summary(cdo.dt))

tmp <- melt(cdo.dt, id.vars=1:6)
tmp <- tmp[, .(
  value = 100*mean(is.na(value))
), by=.(
  loc_nm, variable, 
  year=year(date), month=factor(format(date, "%b"), month.abb))]

ggplot(tmp, aes(year, month, fill=value)) +
  geom_tile(alpha=.8) +
  scale_fill_wc("#008080", "#ffffff", name=NULL) +
  facet_grid(variable~loc_nm) +
  labs(x=NULL, y=NULL, title="Missing Daily Values (%)") +
  theme_wc(
    legend.position="right", 
    legend.key.height=unit(.16, "npc")
  )

# Describe
tmp <- melt(cdo.dt, id.vars=1:6)
tmp[variable=="prcp", value := fifelse(value > 40, NA_real_, value)]

ggplot(tmp, 
  aes(factor(format(date, "%b"), month.abb), value)) +
  geom_boxplot(aes(fill=variable, color=variable), alpha=.4, outlier.size=.4) +
  facet_grid(variable~loc_nm, scales="free_y") +
  labs(x=NULL, y=NULL, title="Daily Observations (1974-2021)") +
  theme_wc(
    legend.position="none",
    panel.grid.major.x=element_blank()
  )

```

```{r weathercan}

# Weathercan stations
can <- stations_search(coords=dt.gars[1, c(Y,X)], dist=50, interval="hour")
setDT(can)
can[, min(distance)]

# Map


```

