project:
  title: mb-labs
  type: website
  output-dir: _site

website:
  favicon: www/logo.svg
  image: www/logo.svg
  twitter-card: true
  title: Mel's Labs
  site-url: https://mbacou.github.io/mb-labs
  repo-url: https://github.com/mbacou/mb-labs
  repo-actions: [issue]
  description: |
    Playground for consulting and data science projects.

  search:
    location: navbar
    type: overlay

  navbar:
    title: Mel's Labs
    left:
      - text: Notebooks
        file: index.qmd
      - text: Portfolio
        file: portfolio.qmd
      - text: About
        file: about.qmd
    right:
      - icon: rss
        href: index.xml
      - icon: linkedin
        href: https://linkedin.com/in/mbacou
      - icon: github
        href: https://github.com/mbacou/mb-labs

  page-footer:
    left: |
      &copy; Copyright 2022 &mdash; BACOU, Melanie.
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    fontsize: 15.75px
    theme:
      dark: www/theme-dark.scss
      light: www/theme-light.scss
