project:
  title: mb-labs
  type: website
  output-dir: _site

website:
  title: "Mel's Labs"
  favicon: www/favicon.png
  image: www/favicon.png
  twitter-card: true
  site-url: https://mbacou.com
  repo-url: https://github.com/mbacou/mb-labs
  page-navigation: true
  bread-crumbs: false
  description: Playground for consulting and data science projects.

  search:
    location: navbar
    type: overlay
    show-item-context: true

  navbar:
    title: "{{< fa regular compass-drafting >}}   Mel's Labs"
    foreground: gray-800
    background: gray-100
    pinned: false
    toggle-position: right
    left:
      - text: Notebooks
        file: index.qmd
      - text: Portfolio
        file: portfolio.qmd
      - text: About
        file: about/index.qmd
    right:
      - icon: github
        href: https://github.com/mbacou/mb-labs
      - icon: telegram
        href: t.me/mbacou
      - icon: linkedin
        href: https://linkedin.com/in/mbacou
      - icon: youtube
        href: https://www.youtube.com/@mbacou/playlists

  page-footer:
    foreground: dark
    background: transparent
    right: |
      All views here are strictly my own and do <u>not</u> reflect that of employers,
      project partners or clients. Refer to each article for citation, code and data reuse.
    left: |
      BACOU, Melanie &copy; 2024

      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/).
    center:
      - text: About
        href: about/index.qmd
      - text: License
        href: license.qmd
      - text: RSS
        href: index.xml
      - text: Built with Quarto^®^
        href: https://quarto.org

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    link-external-icon: false
    link-external-newwindow: true

    fig-dpi: 220
    fig-format: svg
    fig-width: 7
    fig-height: 4.5

    code-copy: true
    code-overflow: wrap

    tbl-cap-location: bottom
    fig-cap-location: bottom
    reference-location: margin
    citation-location: document

    theme: www/theme-news.scss
    fontsize: 16px
    title-block-banner: transparent
    grid:
      body-width: 900px
      sidebar-width: 160px
      margin-width: 240px
      gutter-width: 2em
