project:
  title: mb-labs
  type: website
  output-dir: _site

website:
  title: "Mel's Labs"
  favicon: "www/logo.svg"
  image: "www/logo.svg"
  twitter-card: true
  site-url: https://mbacou.github.io/mb-labs
  repo-url: https://github.com/mbacou/mb-labs
  repo-actions: []
  page-navigation: true
  bread-crumbs: false
  description: |
    Playground for consulting and data science projects.

  search:
    location: navbar
    type: overlay
    show-item-context: true

  navbar:
    title: "Mel's Labs"
    background: dark
    border: true
    logo: www/linkedin.jpg
    logo-alt: "Mel's Labs logo"
    collapse-below: lg

    left:
      - text: Notebooks
        file: index.qmd
      - text: Portfolio
        file: portfolio.qmd
      - text: About
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/mbacou/mb-labs
      - icon: linkedin
        href: https://linkedin.com/in/mbacou
      - icon: rss
        href: index.xml

  page-footer:
    left: |
      &copy; Copyright 2024 &mdash; BACOU, Melanie.
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right: |
      Site built with [Quarto](https://quarto.org/)

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    link-external-icon: false
    link-external-newwindow: true

    code-copy: true
    code-overflow: wrap
    code-block-bg: "var(--bs-white)"
    title-block-banner: "var(--bs-body-bg)"

    tbl-cap-location: margin
    reference-location: margin
    citation-location: margin
    fig-cap-location: margin

    theme: www/theme-light.scss

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
