---
page-layout: full
toc: false
listing:
  id: lst-home
  contents: posts
  categories: false
  feed: true
  filter-ui: false
  sort-ui: false
  sort: "date desc"
  type: grid
  max-items: 9
  fields: [title, description, image, date, author, categories]
---

# Econometric and Geospatial Analysis {.title}

To inform robust and equitable public policy.

----------

<div class="parallax-container"><div class="parallax-image-container"></div></div>

A personal Blog largely centered around R programming and statistical analysis for **agricultural economic research** -- but you'll also find book and article reviews, and the occasional opinion piece. Check out my [full Bio](./about/index.qmd) for details.

This is a line of content before the listing[^1].


Quarto provides a default layout for HTML pages that should work well for many documents. However, if the default layout isn’t working for your content, you can adjust it.

On this page, learn about:

The three high level layout options for your pages in Page Layout.

How to adjust the width of the individual layout components (sidebar, body, margins, and gutter) to fit your content in Grid Customization.


::: {#lst-home}
:::


  
