---
title: Canadian Surface Prediction Archive (CaSPAr)
description: |
  CaSPAr provides easily accessible archives for a range of Environment and Climate Change Canada's operational numerical weather predictions for researchers and end-users. CaSPAr was formed by a partnership between the NSERC Canadian FloodNet, Environment and Climate Change Canada, Esri Canada and several Canadian universities such as the University of Waterloo and McMaster University.
author:
  - name: Melanie Bacou 
    url: https://linkedin.com/in/mbacou
    affiliation: WorldCover PBC
    affiliation_url: https://worldcovr.com/
date: 2021-04-02
categories:
  - meteo
  - risk modeling
output:
  distill::distill_article:
    self_contained: false
---

Testing data retrieval methods from [U. of Waterloo](https://caspar-data.ca/caspar).

```{r}

library(maptiles)
library(terra)
library(wcutils)
dir <- getOption("wc.data")

r <- rast(file.path(dir, "./CaSPAr/CaPA_fine_A_PR_SFC/2018020218.nc"))
r <- project(r, "epsg:4326")

```

```{r, eval=FALSE}

bmap <- get_tiles(ext(r), "OpenStreetMap", crop=T, zoom=6)
writeRaster(bmap, "bmap.tif", overwrite=T)

```

```{r, dev="ragg_png"}

bmap <- rast("bmap.tif")

par(font.main=1, cex.axis=.8)
plot(r, asp=1, main="CaPA_fine_A_PR_SFC Model 2018-02-02 18:00 UTC (mm)")
plot(crop(bmap, r), add=T)
plot(r, border=0, alpha=.5, add=T, legend=F)
grid()

```



